riscv-non-isa/riscv-rpmi

src/srvgrp-device-power.adoc
Rename service name of service group device power
to be consistent with other similar service group.
=> srvgrp-device-power: Rename Device Power Service Name

src/srvgrp-performance.adoc
The request of 'GET_PERF_DOMAIN_FAST_CHANNEL_ADDR' requires additional field to differentiate the
fast channel address of level/limit get/set.
=> srvgrp-device-power: Add request field for get fast channel service id

riscv-rpmi.adoc, src/intro.adoc, src/rpmi.bib, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-device-power.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-voltage.adoc, src/transport.adoc
Update Fast-channel description and some chapters.
=> Update RPMI spec

src/srvgrp-performance.adoc
Performance level to represent as clock frequency
rather than unique ID.
=> perf: Represent performance level as clock frequency

riscv-rpmi.adoc, src/srvgrp-ras-agent.adoc
In ACPI systems, The RAS_AGENT works as a bridge
between the RISCV RERI compliant error sources in
the system and the APEI tables. One of its job is
the populate CPER records when errors occur.
The RAS_AGENT has complete knowledge of the error
sources present in the system and errors they can
generate. The services in the RAS_AGENT service group respond to
- Enumeration of various error sources present in the system
- Get the error source descriptor for an error source
These services from RAS_AGENT can be used to populate the HEST table when ACPI tables are being generated.
For non-ACPI systems also, the error sources can be enumerated. The format for the error source descriptor is left to the implementation.
Signed-off-by: Himanshu Chauhan <hchauhan@ventanamicro.com>
=> Add RAS_AGENT Service Group

src/srvgrp-clock.adoc, src/srvgrp-device-power.adoc, src/srvgrp-performance.adoc, src/srvgrp-voltage.adoc
Combine return format as single array.
=> service group: Combine return format as array

README.adoc, src/intro.adoc, src/srvgrp-clock.adoc, src/srvgrp-device-power.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-voltage.adoc
- Standardize the use 'application processor' and 'platform microcontroller'
- Change to use SERVICEGROUP_ID
- Add SERVICE_ID for each service.
=> Fix format new

src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-device-power.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc
- Update error codes
- Reformating table in *.adoc (no change in generated pdf display)
=> Improve spec

src/message-protocol.adoc, src/service-groups.adoc, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-device-power.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc
- improves RAS, MM, and Device power chapters.
=> Improve spec part2

src/srvgrp-clock.adoc, src/srvgrp-voltage.adoc
Update voltage service group formating and
error codes.
=> voltage: Update formating

src/rpmi.bib, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-device-power.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-voltage.adoc
- rearrange bit fields
- Fine-tune some descriptions
- Add reference link for hart state and suspend type.
=> Spec update

src/rpmi-mpxy.adoc, src/srvgrp-cppc.adoc
Remove the Hard ID parameter from Fastchannel region request
Convert functions names to monospace in rpmi mpxy chapter
Add Perf Feedback Fastchannel in CPPC ServiceGroup
=> CPPC Service group improvements

src/srvgrp-system-suspend.adoc
Not every RISC-V implementation may support the WFI instruction for entering into the quiesced state.
So, make the requirement generic to allow platform supported mechanisms.
#65
=> Relax the WFI instruction requirement in system suspend

riscv-rpmi.adoc, src/message-protocol.adoc, src/service-groups.adoc, src/srvgrp-request-forward.adoc
Certain use-cases require forwarding RPMI messages from one RPMI client to another so let's define request forward service group for this purpose.
=> Define request forward service group

src/message-protocol.adoc
Allow vendor specific error code range to also include Implementation specific error codes also.
Vendor and implementation both can define their error codes which will not be exposed in the specification. So allow implementation also to use this range.
=> Expand the error range to allow Implementation specific codes

src/intro.adoc, src/message-protocol.adoc, src/rpmi-mpxy.adoc, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-device-power.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-request-forward.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc, src/srvgrp-voltage.adoc, src/transport.adoc
Fixes grammars and rephrased some sentences for concisens.
=> Improves all chapters

src/intro.adoc, src/message-protocol.adoc, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc, src/srvgrp-voltage.adoc, src/terms.adoc
These are only fixes to the existing specification which are misleading and incorrect.
=> Fixes across specification in the post ARC review spec

src/srvgrp-device-power.adoc
Update based on feedback from ARC review.
https://github.com/riscv-non-isa/riscv-rpmi/issues/79
=> device-power: Update ON/OFF states in POWER_STATE

src/message-protocol.adoc, src/rpmi-mpxy.adoc, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-device-power.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-request-forward.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc, src/srvgrp-voltage.adoc, src/transport.adoc
=> ARC Feedback Updates in Message protocol, Transport, Base, CPPC

src/srvgrp-clock.adoc, src/srvgrp-performance.adoc, src/srvgrp-voltage.adoc
Add 'PERF_GET_FAST_CHANNEL_REGION' service to get a continuous block of physical memory region for fast channel access.
=> rpmi: performance: Add memory region service

src/srvgrp-performance.adoc
- Fix rate_limit to transition_latency
- Add more descriptions for PERF_SET_LIMIT
https://github.com/riscv-non-isa/riscv-rpmi/issues/79#issuecomment-2559059036
=> performance: Update based on ARC review

riscv-rpmi.adoc, src/message-protocol.adoc, src/rpmi-mpxy.adoc, src/service-groups.adoc, src/srvgrp-base.adoc, src/srvgrp-clock.adoc, src/srvgrp-cppc.adoc, src/srvgrp-device-power.adoc, src/srvgrp-hart-state-management.adoc, src/srvgrp-management.adoc, src/srvgrp-performance.adoc, src/srvgrp-ras-agent.adoc, src/srvgrp-request-forward.adoc, src/srvgrp-system-msi.adoc, src/srvgrp-system-reset.adoc, src/srvgrp-system-suspend.adoc, src/srvgrp-voltage.adoc, src/transport.adoc
This PR factors-out MSI support in BASE service group to a more generic SYSTEM_MSI service group which manages system MSIs from platform microcontroller.
=> Add SYSTEM_MSI service group

src/message-protocol.adoc, src/transport.adoc
To make the message protocol independent from transport, move the doorbell interrupt detials into a separate chapter in RPMI transport which explains how the RPMI transport integrates with RPMI message protocol.
This addresses the pending comment from Ved here https://github.com/riscv-non-isa/riscv-rpmi/issues/90
=> transport: msgprot: Move the doorbell interrupt flag in transport

src/srvgrp-clock.adoc, src/transport.adoc
Update the transport chapter to mention about the physical memory attributes requirements for both AP and PuC.
For clock group changes, these changes are done based on the ARC comment on voltage service group where when the voltage levels format is linear, a voltage domain may support multiple linear ranges which are packed sequentially in message. This is also valid for the clock rates so updating the clock service group
=> Update transport memory attributes details and clock rates data layout based on ARC feedback
